### ISSUE TITLE
require() of ES Module not supported error.

### ISSUE THREAD

**Issue by JongtaekChoi** [dooboolab/dooboo-cli#83]
Recently, I installed dooboo-cli and run it then below error messages are displayed.

```bash
/Users/buba1/.config/yarn/global/node_modules/dooboo-cli/lib/utils/functions.js:16
const chalk_1 = __importDefault(require("chalk"));
                                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/buba1/.config/yarn/global/node_modules/dooboo-cli/node_modules/chalk/source/index.js from /Users/buba1/.config/yarn/global/node_modules/dooboo-cli/lib/utils/functions.js not supported.
Instead change the require of index.js in /Users/buba1/.config/yarn/global/node_modules/dooboo-cli/lib/utils/functions.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/buba1/.config/yarn/global/node_modules/dooboo-cli/lib/utils/functions.js:16:33)
    at Object.<anonymous> (/Users/buba1/.config/yarn/global/node_modules/dooboo-cli/lib/bin/root.js:18:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.2.0
```

How can I resolve it?

**Comment by hyochan** [comment]
@JongtaekChoi Thanks for the issue! This will be fixed in `7.2.0`
